import requests

URL = "https://data.cityofchicago.org/api/views/ygr5-vcbg/rows.csv"
r = requests.get(URL)
DATA = r.text


COLOR_CODE = {'BLK': 'Black', 'CRM': 'Cream/Ivory', 'GRY': 'Gray', 'WHI': 'White',
              'ONG': 'Orange', 'PNK': 'Pink', 'RED': 'Red', 'YEL': 'Yello', 'AME': 'Amethyst',
              'MAR': 'Maroon', 'LAV': 'Lavender', 'MVE': 'Mauve', 'PLE': 'Purple',
              'BGE': 'Beige', 'BRO': 'Brown', 'CAM': 'Camouflage', 'TAN': 'Tan',
              'TPE': 'Taupe', 'BLU': 'Blue', 'DBL': 'Dark Blue', 'LBL': 'Light Blue',
              'GRN': 'Green', 'DGR': 'Dark Green', 'LGR': 'Light Green', 'TEA': 'Teal',
              'TRQ': 'Turquoise', 'SIL': 'Silver', 'BRZ': 'Bronze', 'COM': 'Stainless Steel',
              'CPR': 'Copper', 'GLD': 'Gold', '_NA': ' No Color'}

MAKE_CODE = {"ACUR": "Acura", "FERR": "Ferrari", "MNNI": "Mini", "ALFA": "Alfa Romeo ", "FIAT": "Fiat",
             "MITS": "Mitsubishi ", "ALLS": "All State", "FSKR": "Fisker ", "MONA": "Monarch", "AMER": "Ambassador ",
             "FORD": "Ford", "MORG": "Morgan ", "AMER": "American", "ZCZY": "Formerly Yugo", "MORR": "Morris ",
             "ASVE": "Assembled", "FRAZ": "Frazier", "NASH": "Nash", "ASTO": "Aston-Martin", "GEO": "Geo",
             "NISS": "Nissan", "AUBU": "Auburn", "GMC": "Gmc", "OLDS": "Oldsmobile", "AUDI": "Audi", "HILL": "Hillman",
             "OPEL": "Opel", "AUST": "Austin", "HMDE": "Homemade", "PACK": "Packard", "AUHE": "Austin-Healy",
             "HOND": "Honda", "PEUG": "Peugeot", "AUTO": "Autocar", "HUDS": "Hudson", "PRCA": "Pierce Arrow",
             "AVTI": "Avanti", "AMGN": "Hummer", "PINI": "Pininfarina", "BENT": "Bentley", "HUMM": "Hummer ",
             "PLYM": "Plymouth", "BERO": "Bertone", "HYUN": "Hyundai", "PONT": "Pontiac", "BMW": "BMW",
             "IMPE": "Imperial", "PORS": "Porsche", "BRDL": "Bradley Gt", "INFI": "Infiniti", "RAM": "Ram",
             "BRIC": "Bricklin", "INTL": "Intl Harvester", "RAMB": "Rambler", "BUGA": "Bugatti", "ISET": "Isetta ",
             "RELA": "Reliant", "BUIC": "Buick", "ISU": "Isuzu", "RENA": "Renault", "CADI": "Cadillac",
             "JAGU": "Jaguar", "ROL": "Rolls-Royce", "CAP": "Capri", "JEEP": "Jeep", "ROOT": "Rootes ", "CHEC": "Checker",
             "JENS": "Jensen ", "ROV": "Rover", "CHEV": "Chevrolet", "KAIS": "Kaiser", "SAA": "Saab", "CHRY": "Chrysler",
             "KIA": "Kia", "SATR": "Saturn ", "CITR": "Citroen", "LALL": "La Salle", "SHEB": "Shelby ", "CONC": "Concord",
             "LADA": "Lada", "SHOP": "Shopmade", "CONH": "Condor ", "LAMO": "Lamborghini", "SIAT": "Siata",
             "LINC": "Continental", "LNCI": "Lancia", "SIM": "Simca", "CROS": "Crosley", "LNDR": "Land Rover ",
             "SMRT": "Smart", "DAEW": "Daewoo ", "LEXS": "Lexus", "STLG": "Sterling", "DAIH": "Daihatsu", "LINC":
             "Lincoln", "STU": "Studebaker ", "DAIM": "Daimler", "LINC": "Lincoln-Cont", "STUZ": "Stutz", "DATS":
             "Datsun ", "LOTU": "Lotus", "SUBA": "Subaru ", "DAYO": "Daytona", "MASE": "Maserati", "SUNB": "Sunbeam",
             "DELO": "De Lorean", "AMER": "Matador", "SUZI": "Suzuki ", "DESO": "De Soto", "MAXL": "Maxwell",
             "TOYT": "Toyota", "DETO": "De Tomaso", "MAZD": "Mazda", "TRIU": "Triumph", "DODG": "Dodge",
             "MERZ": "Mercedes-Benz", "VAUX": "Vauxhall", "DUES": "Duesenberg ", "MERC": "Mercury", "VESP": "Vespa", "EGIL":
             "Eagle(auto)", "MERK": "Merkur ", "VOLK": "Volkswagen ", "EDSE": "Edsel", "METR": "Metropolitan",
             "VOLV": "Volvo", "ESSE": "Essex", "MG": "MG", '_NA': ' No Make'}

STATE = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MP': 'Northern Mariana Islands',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NA': 'National',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming',
    '_N': 'No State'
}

